export const LIST_CONTENT = [
  {
    id: 1,
    image: "/content/contentImage/content-1.jpg",
    title: "Big 4 Auditor Financial Analyst",
    desc: "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan kurikulum terbaik",
    imageProfile: "/content/profileMentor/Avatar.png",
    name: "Jenna Ortega",
    job: "Senior Accountant di Gojek",
    imageRating: "content/rating/Rating.png",
    rating: 3.5,
    reviewCount: 86,
    price: "RP 300K",
  },

  {
    id: 2,
    image: "/content/contentImage/content-2.jpg",
    title: "Big 4 Auditor Financial Analyst",
    desc: "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan kurikulum ",
    imageProfile: "/content/profileMentor/Avatar-1.png",
    name: "Jenna Ortega",
    job: "Senior Accountant di Gojek",
    imageRating: "content/rating/Rating.png",
    rating: 3.5,
    reviewCount: 86,
    price: "RP 300K",
  },

  {
    id: 3,
    image: "/content/contentImage/content-3.jpg",
    title: "Big 4 Auditor Financial Analyst",
    desc: "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan kurikulum ",
    imageProfile: "/content/profileMentor/Avatar-2.png",
    name: "Jenna Ortega",
    job: "Senior Accountant di Gojek",
    imageRating: "content/rating/Rating.png",
    rating: 3.5,
    reviewCount: 86,
    price: "RP 300K",
  },

  {
    id: 4,
    image: "/content/contentImage/content-4.jpg",
    title: "Big 4 Auditor Financial Analyst",
    desc: "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan kurikulum ",
    imageProfile: "/content/profileMentor/Avatar-3.png",
    name: "Jenna Ortega",
    job: "Senior Accountant di Gojek",
    imageRating: "content/rating/Rating.png",
    rating: 3.5,
    reviewCount: 86,
    price: "RP 300K",
  },

  {
    id: 5,
    image: "/content/contentImage/content-5.jpg",
    title: "Big 4 Auditor Financial Analyst",
    desc: "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan kurikulum ",
    imageProfile: "/content/profileMentor/Avatar-4.png",
    name: "Jenna Ortega",
    job: "Senior Accountant di Gojek",
    imageRating: "content/rating/Rating.png",
    rating: 3.5,
    reviewCount: 86,
    price: "RP 300K",
  },

  {
    id: 6,
    image: "/content/contentImage/content-6.jpg",
    title: "Big 4 Auditor Financial Analyst",
    desc: "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan kurikulum ",
    imageProfile: "/content/profileMentor/Avatar-5.png",
    name: "Jenna Ortega",
    job: "Senior Accountant di Gojek",
    imageRating: "content/rating/Rating.png",
    rating: 3.5,
    reviewCount: 86,
    price: "RP 300K",
  },

  {
    id: 7,
    image: "/content/contentImage/content-7.jpg",
    title: "Big 4 Auditor Financial Analyst",
    desc: "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan kurikulum ",
    imageProfile: "/content/profileMentor/Avatar-6.png",
    name: "Jenna Ortega",
    job: "Senior Accountant di Gojek",
    imageRating: "content/rating/Rating.png",
    rating: 3.5,
    reviewCount: 86,
    price: "RP 300K",
  },

  {
    id: 8,
    image: "/content/contentImage/content-8.jpg",
    title: "Big 4 Auditor Financial Analyst",
    desc: "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan kurikulum ",
    imageProfile: "/content/profileMentor/Avatar-7.png",
    name: "Jenna Ortega",
    job: "Senior Accountant di Gojek",
    imageRating: "content/rating/Rating.png",
    rating: 3.5,
    reviewCount: 86,
    price: "RP 300K",
  },

  {
    id: 9,
    image: "/content/contentImage/content-3.jpg",
    title: "Big 4 Auditor Financial Analyst",
    desc: "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan kurikulum ",
    imageProfile: "/content/profileMentor/Avatar-8.png",
    name: "Jenna Ortega",
    job: "Senior Accountant di Gojek",
    imageRating: "content/rating/Rating.png",
    rating: 3.5,
    reviewCount: 86,
    price: "RP 300K",
  },
];
